### ISSUE TITLE
Implement remix-dev for Easier Testing

### ISSUE THREAD

**Issue by cheesea3** [imperfectandcompany/Imperfect-Gamers-Site-Store#21]
### Description
As a developer, I want to integrate remix-dev to simplify our development process by enabling live-reloading, thereby speeding up iteration on code changes and improving productivity.

### Task List:
- [x] Configure remix-dev within the project.
- [x] Test live-reloading features.
- [x] Document the setup process and usage guidelines.
