### ISSUE TITLE
Set Up Dev Branch, Rename Master to Production

### ISSUE THREAD

**Issue by cheesea3** [imperfectandcompany/Imperfect-Gamers-Site-Store#26]
### Description:
Optimize our repository structure by setting up a dedicated development branch and renaming the master branch to better reflect its role as our production environment.

### Task List:

- [x] Create a new 'dev' branch for development purposes.
- [x] Rename 'master' branch to 'production' to clarify its use.
- [x] Update repository documentation and CI/CD pipelines to reflect these changes.
