### ISSUE TITLE
Setup GitHub Action to Build Docker Image

### ISSUE THREAD

**Issue by cheesea3** [imperfectandcompany/Imperfect-Gamers-Site-Store#34]
### Description:
Automate the process of Docker image creation for the application by setting up a GitHub Action, enhancing deployment efficiency and consistency.

### Task List:

- [x] Develop a GitHub Action script to build Docker images upon new commits.
- [x] Configure Docker environments and dependencies.
- [x] Test the automated Docker build process to ensure reliability.
